
project_id = "zaitoudikrddbzsfukzv"
[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 604800

[storage]
enabled = true

[functions]
[functions.check_favorite]
verify_jwt = true
