apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-frontend
  template:
    metadata:
      labels:
        app: vite-frontend
    spec:
      containers:
        - name: vite
          image: joakimfellbom/editoreasy-showcase:latest
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: vite-frontend
spec:
  type: NodePort
  selector:
    app: vite-frontend
  ports:
    - port: 80
      targetPort: 4173
      nodePort: 30080